M48
; DRILL file {KiCad 8.0.0} date 2026-04-18T16:36:20+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-18T16:36:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.3307
%
G90
G05
T1
X4.911Y-2.2954
X4.911Y-3.8702
X8.8638Y-2.2954
X8.8638Y-3.8702
T2
X6.8874Y-1.4627
M30
